### ISSUE TITLE
How do I creat ADDSENTMOD

### ISSUE THREAD

**Issue by ghost** [robinjia/adversarial-squad#1]
Hi,I want to conduct an experiment just like what you did in section 4.6 of your paper on my own model. How should I do? Thanks

**Comment by robinjia** [comment]
The "Retraining BiDAF" section of [the codalab worksheet](https://worksheets.codalab.org/worksheets/0xc86d3ebe69a3427d91f9aaa63f7d1e7d/) describes how this is done.  From there, you can download the AddSentMod dataset (it is called [`sample1k-HCVerifyModAll.json`](https://worksheets.codalab.org/bundles/0x3ed0adecdead49749c1db711e85fdf26/)).  Does this fit your needs?

**Comment by ghost** [comment]
I found it.Thanks.
