### ISSUE TITLE
Downloading the adversarial dataset 

### ISSUE THREAD

**Issue by sudarshan1994** [robinjia/adversarial-squad#3]
I am not able to find the adversarial dataset in the Codalabs link, could you guys please point me to the location of the adversarial dataset in the codalabs page?

**Comment by WangJiuniu** [comment]
I have the some question(～ o ～)~zZ

**Comment by robinjia** [comment]
It's under the section called "AddSent and AddOneSent" under "Main Experiments".  The direct links to the datasets are: [AddSent](https://worksheets.codalab.org/bundles/0xb765680b60c64d088f5daccac08b3905/) [AddOneSent](https://worksheets.codalab.org/bundles/0x3ac9349d16ba4e7bb9b5920e3b1af393/)

**Comment by pminervini** [comment]
@robinjia to reproduce the AddOneSent results, do we need to consider the question-answer pairs with `-high-conf-turk` in their ID, or all of them?

**Comment by robinjia** [comment]
Hi,

You should consider all of them. In particular, for each original example, the evaluation returns the worse out of the model's accuracy on the original, and on the example with one added sentence. Please see the [evaluation script](https://worksheets.codalab.org/bundles/0xc2824269ba0a4179ac63c08fd3997d1c) for more details
