### ISSUE TITLE
LICENCE file ?

### ISSUE THREAD

**Issue by thomwolf** [robinjia/adversarial-squad#4]
Hi Robin and Percy,

Could you add a LICENCE to this repo so we know under what terms we can reuse the code?

The MIT licence is pretty standard if you are not used to these questions (ex: https://github.com/rowanz/swagaf/blob/master/LICENSE, https://github.com/uclmr/adversarial-nli/blob/master/LICENSE) but you may opt for different ways of licencing of course.

Best,

Thomas

**Comment by robinjia** [comment]
Just added the license!
