### ISSUE TITLE
Missing vocab file for AddAny - adversarial_squad.py?

### ISSUE THREAD

**Issue by naveenjafer** [robinjia/adversarial-squad#8]
Hi @robinjia I am trying to run the ADDANY example to generate adversarial samples, could you help me with where I can find the vocab file. I see that one of the inputs vocab_file is a mandatory input. Since I wanted to replicate the results of the papers, it would be better to have the identical file. Could you please point me to the file? TIA.

**Comment by robinjia** [comment]
Hi,

Our [Codalab worksheet](https://worksheets.codalab.org/worksheets/0xc86d3ebe69a3427d91f9aaa63f7d1e7d/) shows all the dependencies and commands needed to reproduce our experiments. For example, see the list of dependencies for this AddAny run https://worksheets.codalab.org/bundles/0x6bc712e6c7214f1aa589687cf8e3deb8 I think you are looking for the brown_english_1k.txt file.
